server:
  port: 8070
spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  kafka:
    bootstrap-servers: "localhost:9092"
    producer:
      key-serializer: org.apach.kafka.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: "user-consumer"
      key-deserializer: org.apach.kafka.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            trusted:
              packages: "com.fastcampus.*"

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace